In [1]:
import numpy as np

zeros1 = np.zeros(3)
print(zeros1)

zeros = np.zeros((2, 3))
print(zeros)

ones = np.ones((3, 3))
print(ones)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [1]:
import numpy as np

arr = np.array([[1, 2],[3, 4]])
print(arr.size)

arr1 = np.array([[1, 2, 3],[2, 3, 4],[4, 5, 5],[6, 7, 6]])
print(arr1.size)
print(arr1)
print(arr)
print(type(arr))

4
12
[[1 2 3]
 [2 3 4]
 [4 5 5]
 [6 7 6]]
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

a = np.arange(1, 7)
print(a)

b = a.reshape(3, 2)
print(b)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
